# Generated by Django 4.2.23 on 2025-08-13 06:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_code', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('car', 'Car'), ('bicycle', 'Bicycle'), ('walk', 'Walking')], default='bike', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_documents', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_break', 'On Break'), ('off_duty', 'Off Duty')], default='inactive', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('average_delivery_time_minutes', models.PositiveIntegerField(default=0)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission per delivery', max_digits=5)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agents', to='stores.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_agents',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delivery_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_delivery_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('customer_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliveryagent')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order')),
            ],
            options={
                'db_table': 'delivery_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('route_coordinates', models.JSONField(default=list, help_text='Array of [lat, lng] coordinates for the route')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='delivery.deliveryagent')),
            ],
            options={
                'db_table': 'delivery_routes',
                'ordering': ['-date'],
                'unique_together': {('agent', 'date', 'route_name')},
            },
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_method', models.CharField(choices=[('photo', 'Photo'), ('otp', 'OTP'), ('signature', 'Signature'), ('contactless', 'Contactless')], max_length=20)),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('recipient_photo', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('otp_code', models.CharField(blank=True, max_length=10)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature')),
                ('recipient_name', models.CharField(blank=True, max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=15)),
                ('delivery_notes', models.TextField(blank=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='delivery.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_proof_of_delivery',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bearing_degrees', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_updates', to='delivery.deliveryassignment')),
            ],
            options={
                'db_table': 'delivery_tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assignment'], name='delivery_tr_assignm_3d2658_idx'), models.Index(fields=['created_at'], name='delivery_tr_created_0788bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stop_order', models.PositiveIntegerField()),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=5)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='delivery.deliveryassignment')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='delivery.deliveryroute')),
            ],
            options={
                'db_table': 'delivery_route_stops',
                'ordering': ['stop_order'],
                'unique_together': {('route', 'assignment')},
            },
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['agent'], name='delivery_as_agent_i_ab19c9_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['status'], name='delivery_as_status_f43cef_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryassignment',
            index=models.Index(fields=['assigned_at'], name='delivery_as_assigne_c36169_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagent',
            index=models.Index(fields=['agent_code'], name='delivery_ag_agent_c_f75791_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagent',
            index=models.Index(fields=['store'], name='delivery_ag_store_i_e9863e_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryagent',
            index=models.Index(fields=['status'], name='delivery_ag_status_688e8a_idx'),
        ),
    ]
