# Generated by Django 4.2.23 on 2025-08-13 06:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('store_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('fssai_license', models.CharField(blank=True, max_length=14)),
                ('business_license', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended'), ('temporarily_closed', 'Temporarily Closed')], default='pending_approval', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_24_hours', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores_stores',
            },
        ),
        migrations.CreateModel(
            name='StoreClosureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_closure_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_closure_requests', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_requests', to='stores.store')),
            ],
            options={
                'db_table': 'stores_closure_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreZipCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, help_text="Override store's default delivery fee for this ZIP", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Override store's default minimum order amount for this ZIP", max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_time_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_coverages', to='stores.store')),
                ('zip_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_coverages', to='locations.ziparea')),
            ],
            options={
                'db_table': 'stores_zip_coverage',
                'indexes': [models.Index(fields=['zip_area', 'is_active'], name='stores_zip__zip_are_1f64ac_idx'), models.Index(fields=['store', 'is_active'], name='stores_zip__store_i_8584c6_idx')],
                'unique_together': {('store', 'zip_area')},
            },
        ),
        migrations.CreateModel(
            name='StoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('cashier', 'Cashier'), ('inventory', 'Inventory Manager'), ('delivery_coordinator', 'Delivery Coordinator')], max_length=20)),
                ('permissions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('hired_at', models.DateField()),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stores_staff',
                'unique_together': {('store', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoreHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_hours', to='stores.store')),
            ],
            options={
                'db_table': 'stores_hours',
                'unique_together': {('store', 'day')},
            },
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['store_code'], name='stores_stor_store_c_41f9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['status'], name='stores_stor_status_27edb2_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active'], name='stores_stor_is_acti_39ab66_idx'),
        ),
    ]
